### ISSUE TITLE
node app.js install 时报错

### ISSUE THREAD

**Issue by snssv** [zensh/jsgen#76]
rrestjs process 2211 Checking config file starting...
check config file error: TypeError: check[key] is not a function
rrestjs process 2211 Config file checking complete, errors:0/73, warns:0/73
{ [ReferenceError: Invalid left-hand side in assignment] domainThrown: true }
/Users/snssv/nodeapp/jsgen/node_modules/rrestjs/node_modules/mongodb/lib/mongodb/db.js:869
      || (selector['mapreduce'] && selector.out = 'inline')) {
          ^^^^^^^^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by geeeeeeeeek** [comment]
删除、重装。

**Comment by zensh** [comment]
抱歉，这个项目已经停止维护了，因为它的第三方依赖包也很早停止维护了，现在的 node.js 肯定跑不起来了
